### ISSUE TITLE
Bug on FB Messenger

### ISSUE THREAD

**Issue by guhur** [telegraph-ai/giskard#6]
When the bot does not understand a message (here _frgt_), it crashes:

> 173.252.123.141 - - [09/Aug/2016:09:49:23 +0200] "POST /[verify_token]/fbmessenger HTTP/1.1" 500 197078 0.0534
> I, [2016-08-09T09:49:26.982969 #12282]  INFO -- : frgt
> I, [2016-08-09T09:49:26.983503 #12282]  INFO -- : find_by_answer frgt context: home
> I, [2016-08-09T09:49:26.983728 #12282]  INFO -- : dont_understand #<OpenStruct from="1259636124081609", text="frgt">
> I, [2016-08-09T09:49:26.983911 #12282]  INFO -- : find_by_name system/dont_understand
> I, [2016-08-09T09:49:26.984123 #12282]  INFO -- : format_answer: system/dont_understand
> NoMethodError: undefined method `[]' for nil:NilClass
>   /Users/pierre-louis/src/giskard/bot/navigation.rb:184:in`get'
>   /Users/pierre-louis/src/giskard/bot/fbmessenger_bot.rb:127:in `block (2 levels) in <class:FBMessengerBot>'
>   /Users/pierre-louis/src/giskard/bot/fbmessenger_bot.rb:122:in`each'
>   /Users/pierre-louis/src/giskard/bot/fbmessenger_bot.rb:122:in `block in class:FBMessengerBot'
> ...

**Comment by thibauld** [comment]
Does this bug still stand after your PR ?

**Comment by guhur** [comment]
No I close it
